version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: miniopass
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: miniopass
    command:
      [
        'minio',
        'server',
        '/export',
        '--address',
        ':9050',
        '--console-address',
        ':9051'
      ]
    # volumes:
    #   - ./minio_data:/export
    ports:
      - '9050:9050'
      - '9051:9051'

  create_bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc config host add myminio http://minio:9050 root miniopass) do echo '...waiting...' && sleep 1; done; /usr/bin/mc mb myminio/mybucket; /usr/bin/mc anonymous set download myminio/mybucket; exit 0; "
