---
version: '3'
services:
  mockServer:
    image: wiremock/wiremock:latest
    volumes:
      - "./dev/wiremock/:/home/wiremock/"
    ports:
      - 9000:8080
    restart: on-failure
    command:
      - --verbose
      - --disable-banner
